### ISSUE TITLE
Blink on initial load

### ISSUE THREAD

**Issue by pronevich** [smooth-code/website#17]
I think you know this issue. I interested in what caused it (ssr + loadable-components ?) and how to avoid this.

**Comment by neoziro** [comment]
@pronevich I had several issues :

- primary [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components) doesn't work very well with `extend`
- secondary, [loadable-components](https://github.com/smooth-code/loadable-components) doesn't completely support preload, I will fix it today

A PR of fixes : https://github.com/smooth-code/website/pull/18

**Comment by neoziro** [comment]
@pronevich there was also HTML minification from Cloudflare that broke React re-hydratation. Now everything is fixed.
